language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: precise
      r: 3.5.3
    - dist: trusty
    - dist: xenial
    - os: osx

addons:
  apt:
    packages:
      - libssl-dev
