language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: xenial
      r_check_args: '--use-valgrind'
    - os: linux
    - os: osx

addons:
  apt:
    packages:
      - libssl-dev
      - valgrind

notifications:
  email:
    on_success: change
    on_failure: change
